#### 1. Demonstrate three different methods for creating identical 2D arrays in NumPyƒ Provide the code for each 
method and the final output after each method‚

In [1]:
import numpy as np

# Method 1: Using np.array
array_1 = np.array([[1, 2, 3], [4, 5, 6]])

print("Array 1:")
print(array_1)


Array 1:
[[1 2 3]
 [4 5 6]]


In [2]:
# Method 2: Using np.ones
array_2 = np.ones((2, 3)) * np.array([1, 2, 3])

print("\nArray 2:")
print(array_2)



Array 2:
[[1. 2. 3.]
 [1. 2. 3.]]


In [3]:
# Method 3: Using np.full
array_3 = np.array([np.full(3, i) for i in [1, 2, 3]])

print("\nArray 3:")
print(array_3)



Array 3:
[[1 1 1]
 [2 2 2]
 [3 3 3]]


#### 2. Using the Numpy function, generate an array of 100 evenly spaced numbers between 1 and 10 and 
Reshape tha 1wD array into a 2D arra.‚

In [4]:
import numpy as np

# Generate 100 evenly spaced numbers between 1 and 10
array_1d = np.linspace(1, 10, 100)

# Reshape the array into a 2D array (e.g., 10x10)
array_2d = array_1d.reshape(10, 10)

print(array_2d)


[[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
   1.54545455  1.63636364  1.72727273  1.81818182]
 [ 1.90909091  2.          2.09090909  2.18181818  2.27272727  2.36363636
   2.45454545  2.54545455  2.63636364  2.72727273]
 [ 2.81818182  2.90909091  3.          3.09090909  3.18181818  3.27272727
   3.36363636  3.45454545  3.54545455  3.63636364]
 [ 3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
   4.27272727  4.36363636  4.45454545  4.54545455]
 [ 4.63636364  4.72727273  4.81818182  4.90909091  5.          5.09090909
   5.18181818  5.27272727  5.36363636  5.45454545]
 [ 5.54545455  5.63636364  5.72727273  5.81818182  5.90909091  6.
   6.09090909  6.18181818  6.27272727  6.36363636]
 [ 6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
   7.          7.09090909  7.18181818  7.27272727]
 [ 7.36363636  7.45454545  7.54545455  7.63636364  7.72727273  7.81818182
   7.90909091  8.          8.09090909  8.18181818]
 [ 8.272

#### 3. Explain the following terms:
1.  The difference in n.arrray, n.Yasarray and n.YasanyarraX2. M The difference between Deep copy and shallow copy

np.array: This function creates a new NumPy array from a list, tuple, or other array-like objects.

np.asarray: This function converts input data into an array but doesn’t make a copy if the input is already a NumPy array.

np.asanyarray: Similar to np.asarray, but if the input is a subclass of ndarray, like a matrix, it preserves the subclass type.

Deep copy vs. Shallow copy:

Shallow copy: Only references are copied; changes to the copied object will affect the original.
Deep copy: A completely new object is created; changes to the copy do not affect the original.

#### 4. Generate a 3X3 array with random floating-point numbers between 5 and 20 then, round each number in 
the array to 2 decima places8

In [5]:
# Generate the array
array_random = np.random.uniform(5, 20, (3, 3))

# Round the numbers to 2 decimal places
array_rounded = np.round(array_random, 2)

print(array_rounded)


[[14.73 13.02 15.1 ]
 [ 6.34 15.68  5.9 ]
 [ 9.94  8.53 19.86]]


#### 5. Create a NumPy array with random integers between 1 and 10 of shape (5,6). After creating the array 
perform the following operations:

 a)Extract all even integers from array.

 b)Extract all odd integers from array

In [6]:
# Create a random integer array of shape (5, 6)
array_integers = np.random.randint(1, 11, (5, 6))

# Extract even integers
even_integers = array_integers[array_integers % 2 == 0]

# Extract odd integers
odd_integers = array_integers[array_integers % 2 != 0]

print("Even integers:", even_integers)
print("Odd integers:", odd_integers)


Even integers: [ 6  6  4  6  2 10 10  8  8  6  4  4  2]
Odd integers: [5 7 7 1 1 1 5 9 9 5 5 9 9 1 7 5 9]


#### 6. Create a 3D NumPy array of shape (3, 3, 3) containing random integers between 1 and 10 Perform the 
following operations:

 a) Find the indices of the maximum values along each depth level (third axis).

 b) Perform elementwise multiplication of between both arrayX

In [7]:
# Create a 3D array with random integers between 1 and 10
array_3d = np.random.randint(1, 11, (3, 3, 3))

# Find indices of max values along the third axis
indices_max = np.argmax(array_3d, axis=2)

# Element-wise multiplication (e.g., multiplying array by itself)
elementwise_multiplication = array_3d * array_3d

print("Indices of max values:", indices_max)
print("Element-wise multiplication:\n", elementwise_multiplication)


Indices of max values: [[0 2 1]
 [0 1 1]
 [0 1 2]]
Element-wise multiplication:
 [[[ 16  16   9]
  [  9   4 100]
  [  4  81   9]]

 [[ 49   4  49]
  [ 16 100 100]
  [  4  81  25]]

 [[100  64  16]
  [ 36  64   4]
  [  9   1 100]]]


#### 7. Clean and transform the 'Phone' column in the sample dataset to remove non-numeric characters and
convert it to a numeric data typ.ƒ Also display the tbPle attrbPutes and data types of each colum‚

In [16]:
import pandas as pd

# Sample DataFrame with a 'Phone' column containing non-numeric characters
df=pd.read_csv(r"C:\Users\Dell\Downloads\People Data.csv")

Index          User Id First Name Last Name  Gender  \
0        1  8717bbf45cCDbEe     Shelia   Mahoney    Male   
1        2  3d5AD30A4cD38ed         Jo    Rivers  Female   
2        3  810Ce0F276Badec     Sheryl    Lowery  Female   
3        4  BF2a889C00f0cE1    Whitney    Hooper    Male   
4        5  9afFEafAe1CBBB9    Lindsey      Rice  Female   
..     ...              ...        ...       ...     ...   
995    996  fedF4c7Fd9e7cFa       Kurt    Bryant  Female   
996    997  ECddaFEDdEc4FAB      Donna     Barry  Female   
997    998  2adde51d8B8979E      Cathy  Mckinney  Female   
998    999  Fb2FE369D1E171A   Jermaine    Phelps    Male   
999   1000  8b756f6231DDC6e        Lee      Tran  Female   

                             Email                  Phone Date of birth  \
0              pwarner@example.org           857.139.8239    27-01-2014   
1    fergusonkatherine@example.net                    NaN    26-07-1931   
2              fhoward@example.org          (599)782-0605    25-11-2013   
3            zjohnston@example.com                    NaN    17-11-2012   
4                 elin@example.net     (390)417-1635x3010    15-04-1923   
..                             ...                    ...           ...   
995         lyonsdaisy@example.net           021.775.2933    05-01-1959   
996        dariusbryan@example.com   001-149-710-7799x721    06-10-2001   
997         georgechan@example.org  +1-750-774-4128x33265    13-05-1918   
998            wanda04@example.net          (915)292-2254    31-08-1971   
999        deannablack@example.org     079.752.5424x67259    24-01-1947   

                           Job Title  Salary  
0                  Probation officer   90000  
1                             Dancer   80000  
2                               Copy   50000  
3           Counselling psychologist   65000  
4                Biomedical engineer  100000  
..                               ...     ...  
995                Personnel officer   90000  
996          Education administrator   50000  
997  Commercial/residential surveyor   60000  
998                 Ambulance person  100000  
999       Nurse, learning disability   90000  

[1000 rows x 10 columns]

In [27]:
df["Phone"].fillna(0,inplace=True)
df

Index          User Id First Name Last Name  Gender  \
0        1  8717bbf45cCDbEe     Shelia   Mahoney    Male   
1        2  3d5AD30A4cD38ed         Jo    Rivers  Female   
2        3  810Ce0F276Badec     Sheryl    Lowery  Female   
3        4  BF2a889C00f0cE1    Whitney    Hooper    Male   
4        5  9afFEafAe1CBBB9    Lindsey      Rice  Female   
..     ...              ...        ...       ...     ...   
995    996  fedF4c7Fd9e7cFa       Kurt    Bryant  Female   
996    997  ECddaFEDdEc4FAB      Donna     Barry  Female   
997    998  2adde51d8B8979E      Cathy  Mckinney  Female   
998    999  Fb2FE369D1E171A   Jermaine    Phelps    Male   
999   1000  8b756f6231DDC6e        Lee      Tran  Female   

                             Email                  Phone Date of birth  \
0              pwarner@example.org           857.139.8239    27-01-2014   
1    fergusonkatherine@example.net                      0    26-07-1931   
2              fhoward@example.org          (599)782-0605    25-11-2013   
3            zjohnston@example.com                      0    17-11-2012   
4                 elin@example.net     (390)417-1635x3010    15-04-1923   
..                             ...                    ...           ...   
995         lyonsdaisy@example.net           021.775.2933    05-01-1959   
996        dariusbryan@example.com   001-149-710-7799x721    06-10-2001   
997         georgechan@example.org  +1-750-774-4128x33265    13-05-1918   
998            wanda04@example.net          (915)292-2254    31-08-1971   
999        deannablack@example.org     079.752.5424x67259    24-01-1947   

                           Job Title  Salary  
0                  Probation officer   90000  
1                             Dancer   80000  
2                               Copy   50000  
3           Counselling psychologist   65000  
4                Biomedical engineer  100000  
..                               ...     ...  
995                Personnel officer   90000  
996          Education administrator   50000  
997  Commercial/residential surveyor   60000  
998                 Ambulance person  100000  
999       Nurse, learning disability   90000  

[1000 rows x 10 columns]

In [33]:
df['Phone'] = pd.to_numeric(df['Phone'], errors='coerce')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Index          1000 non-null   int64  
 1   User Id        1000 non-null   object 
 2   First Name     1000 non-null   object 
 3   Last Name      1000 non-null   object 
 4   Gender         1000 non-null   object 
 5   Email          1000 non-null   object 
 6   Phone          126 non-null    float64
 7   Date of birth  1000 non-null   object 
 8   Job Title      1000 non-null   object 
 9   Salary         1000 non-null   int64  
dtypes: float64(1), int64(2), object(7)
memory usage: 78.3+ KB


#### 8. Perform the following tasks using people dataset:

 a) Read the 'datacsv' file using pandas, skipping the first 50 rows.

 b) Only read the columns: 'Last Name', ‘Gender’,’Email’,‘Phone’ and ‘Salary’ from the file.

 c) Display the first 10 rows of the filtered dataset.

 d) Extract the ‘Salary’' column as a Series and display its last 5 valuesX

In [47]:
# a) Read the 'data.csv' file skipping the first 50 rows
people_df=df[]
people_df

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (2451244831.py, line 2)

In [44]:
#b) Only read the specified columns: 'Last Name', 'Gender', 'Email', 'Phone', 'Salary'
filtered_df = people_df['Salary']

KeyError: 'Salary'

#### 9. Filter and select rows from the People_Dataset, where the 'Last Name' column contains the name 'Duke', 
'Gender' column contains the word Female and SNalary’ shouldbPe less than85000                   ‚

In [12]:
# Filter based on the conditions provided
filtered_rows = people_df[(people_df['Last Name'].str.contains('Duke')) & 
                          (people_df['Gender'] == 'Female') & 
                          (people_df['Salary'] < 85000)]
print(filtered_rows)



NameError: name 'people_df' is not defined

#### 10. Create a 7*5 Dataframe in Pandas using a series generated from 35 random integers between 1 to 6?

In [11]:
# Generate 35 random integers between 1 and 6
random_data = np.random.randint(1, 7, 35)

# Create a DataFrame of shape 7x5
df_random = pd.DataFrame(random_data.reshape(7, 5))

print(df_random)


   0  1  2  3  4
0  1  3  4  1  6
1  5  1  4  3  1
2  4  6  1  2  5
3  2  2  4  3  5
4  2  1  2  5  5
5  6  3  5  5  4
6  5  1  1  2  2


#### 

#### 

#### 

#### 

#### 

#### 

#### 

#### 

#### 

#### 

#### 

#### 

#### 

#### 

#### 

#### 

#### 

#### 

#### 

#### 

#### 

#### 

#### 

#### 

#### 

#### 

#### 

#### 